version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    commit_message:
      prefix: "chore"
      include_scope: true
    ignored_updates:
      - match:
          dependency_name: "@types/node"
          version_requirement: ">=10.17"
    automerged_updates:
      - match:
          update_type: "semver:patch"
    default_reviewers:
      - "oBusk"
