version: 1
update_configs:
    - package_manager: "javascript"
      directory: "/"
      update_schedule: "live"
      version_requirement_updates: "increase_versions"
      commit_message:
          prefix: "chore"
          include_scope: true
      ignored_updates:
          - match:
                dependency_name: "@types/node"
                version_requirement: ">=11"
      automerged_updates:
          - match:
                update_type: "semver:patch"
      default_reviewers:
          - "oBusk"
